#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d      
# bspc monitor -d 1 II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer   true

#bspc config normal_frame_opacity 0.75
#bspc config focused_frame_opacity 0.75

bspc config normal_border_color "#2A2426"
bspc config focused_border_color "#9CA1A6"

# xprop | grep WM_CLASS  <<con este comando se puede ver
# el tipo de clase de las aplicaciones 
# para ponerlo en las reglas
bspc rule -a kitty
bspc rule -a Code follow=on
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on
bspc rule -a TelegramDesktop desktop='^4' state=title follow=on
bspc rule -a vlc desktop='^6' follow=on
bspc rule -a obs desktop='^5' follow=on
bspc rule -a krita desktop='^6' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# close all apps
# ~/.config/polybar/launch.sh

killall polybar
killall volumeicon
killall picom
killall dunst
killall nm-applet

# start apps
feh --bg-scale ~/Wall/6.jpg
~/.config/polybar/launch.sh

picom &
volumeicon &
numlockx
xsetroot -cursor_name left_ptr
dunst &
nm-applet &
./.config/bspwm/autorun.py

#nitrogen --restore
# feh --bg-scale --randomize ~/Wall/*
# dusntify dunst
# montando fstab
# /dev/sda1 /run/media/erick/1TD ntfs rw,defaults,umask=0000,uid=1000,gid=1000 0 0
