#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d      
# bspc monitor -d 1 II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# xprop | grep WM_CLASS  <<con este comando se puede ver
# el tipo de clase de las aplicaciones 
# para ponerlo en las reglas
bspc rule -a Tilix
bspc rule -a Code desktop='^1' follow=on
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on
bspc rule -a TelegramDesktop desktop='^5' state=floating follow=on
bspc rule -a vlc desktop='^6' follow=on
bspc rule -a obs desktop='^4' follow=on

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a telegram-desktop desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# close all apps
~/.config/polybar/launch.sh

killall polybar
killall volumeicon
killall picom

# start apps
~/.config/polybar/launch.sh
feh --bg-scale ~/Wall/kitten.jpg
#nitrogen --restore
picom &
volumeicon &
numlockx
xsetroot -cursor_name left_ptr
