#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6
# bspc monitor -d 1 II III IV V VI VII VIII IX X


bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# xprop | grep WM_CLASS  <<con este comando se puede ver
#  la el tipo de clase de las aplicaciones 
# para ponerlo en las reglas
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Tilix state=floating
bspc rule -a Code desktop='^1'
bspc rule -a TelegramDesktop desktop='^4' state=floating


# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a telegram-desktop desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off


# close all apps 
killall polybar
killall dunst
killall picom
killall feh

# start apps
~/.config/polybar/launch.sh
feh --bg-scale ~/Wall/2.jpg
picom &
dunst &
numlockx
xsetroot -cursor_name left_ptr
tilix -e "neofetch"

